//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejercicio1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicio1
    {
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string Nombre { get; set; }
        public string correo { get; set; }
        public string Tipousuario { get; set; }
    }
}
